# Generated by Django 2.2.19 on 2022-02-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220209_1159'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopping_cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shop_user_recipe'),
        ),
    ]
