# Generated by Django 2.2.19 on 2022-02-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220209_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
