# Generated by Django 2.2.19 on 2022-02-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220207_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmcodes',
            options={'verbose_name': 'Код подтверждения', 'verbose_name_plural': 'Коды подтверждения'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='user is active'),
        ),
    ]
